function raster_params = default_plot_raster_params(line_dur)
%

% AF 10/9/01

if (exist('line_dur','var') ~= 1)
   line_dur = 1;
end

raster_params.func = 'default_plot_raster';
raster_params.props.axes = struct( ...
   'Tag',        'raster' ...
   ,'Box',        'on' ...
   ,'Color',     'k' ...
   ,'XLim',      [0 line_dur] ...
   ,'XTick',      [0 line_dur] ...
   );
raster_params.props.line = struct( ...
   'Tag',         'line' ...
   ,'MarkerSize',  4 ...
   ,'Color',     'g' ...
   ,'EraseMode', 'none' ...
   );
raster_params.props.xlabel = struct( ...
   'fontsize',   14 ...
   );
raster_params.props.ylabel = struct( ...
   'fontsize',   14 ...
   );
