function h_fig = strdlg(str, title, max_width, fig_props, list_props)
% h_fig = strdlg(str, title, max_width, fig_props, list_props)

% AF 12/1/01


if ((exist('title','var') ~= 1) | isempty(title))
   title = 'string browser';
end
if (exist('max_width','var')~=1 | isempty(max_width))
   max_width  = Inf;
end

tot_height = min(length(str)+7, 40);
str_width = size(char(str),2);

screen_size  = get_screen_size('char');
% aspec_ratio  = screen_size(3)/screen_size(4);
fig_width = max(60,min(str_width+40,screen_size(3)*0.9));
fig_pos = [(screen_size(3)-fig_width)/2  screen_size(4)-tot_height-4 ...
      fig_width  tot_height];
     
h_fig = figure( ...
   'NumberTitle',         'off',...
   'Name',                title, ...
   'Units',               'char', ...
   'position',            fig_pos, ...
   'MenuBar',             'none', ...
   'KeyPressFcn',         'if isequal(get(gcbf,''CurrentCharacter''),char(13)), delete(gcbf);end', ...
   'color',               get(0,'DefaultuicontrolBackgroundColor'), ...
   'Visible',             'off'... 
   );
%   'KeyPressFcn',         'if get(gcbf,''CurrentCharacter'')==char(10), delete(gcbf);end', ...

if (exist('fig_props','var') ~= 0 & isstruct(fig_props))
   set(h_fig, fig_props);
end

hOK = uicontrol('Parent',   h_fig, ...
   'Style',                'PushButton', ...
   'String',               'OK', ...
   'Units',                'char', ...
   'FontSize',              12, ...
   'Position',              [fig_pos(3)/2-8 0.1 12 1.8], ...
   'CallBack',             'delete(gcbf)', ...
   'BackgroundColor',       get(0,'DefaultuicontrolBackgroundColor') ...
   );

h_list = uicontrol('Parent', h_fig,...
   'Style',                'listbox',...
   'Units',                'char',...
   'Position',              [1 2.5 fig_pos(3)-2 fig_pos(4)-3.5],...
   'HorizontalAlignment',  'left', ...
   'FontName',             'FixedWidth',...
   'FontSize',              9,...
   'Enable',               'inactive',...
   'Value',                 [],...
   'Max',                   tot_height-2, ...
   'BackgroundColor',       [1 1 1], ...
   'String',                str,...
   'Tag',                  'strList', ...
   'Visible',              'off'... 
   );

if (exist('list_props','var') ~= 0 & isstruct(list_props))
   set(h_list, list_props);
end

set(h_list,'Visible','on');
set(h_fig,'Visible','on');


