function my_startup
% MY_STARTUP personlized startup file for nel users

global JB_root_dir JB_exp_type 

JB_root_dir = [fileparts(which('my_startup')) filesep];

addpath([JB_root_dir  'myMfiles']);
addpath([JB_root_dir  'Vowel Synthesis']);
addpath([JB_root_dir  'Templates']);
exp_options = {'F31-AN'};
s = listdlg('PromptString','Select Experiment Type:',...
    'SelectionMode','single',...
    'ListString', exp_options);
JB_exp_type = exp_options{s};

switch (JB_exp_type)
case 'F31-AN'
    JB_Templates = struct(...
        'BF_RLV',                'BF_RLV_template', ...
        'LTASS_RLV',             'LTASSrlv_quick_template', ...
        'EHrlv',                 'EHrlv_template', ...
        'EHrlv_LTASS',           'EHrlv_LTASS_template', ...
        'EH_LTASSrlv',           'EH_LTASSrlv_template', ...
        'EHLTASSvN_reBFi',       'EHLTASSvN_reBFi_template', ...
        'WAV_reBFi',             'WAV_reBFi_template',...
        'EH_reBFi',              'EH_reBFi_template', ...
        'EH_reFF',               'EH_reFF_template' ...
        );
end

register_user_templates(JB_Templates);
